### ISSUE TITLE
is lxml a dependency AND missed?

### ISSUE THREAD

**Issue by amrrs** [amrrs/tiobeindexpy#1]

**Comment by c3cuddles** [comment]
Had a problem that seems to be related. Installed tiobeindexpy in a pipenv. Importing the module failed because I was missing lxml. After running `pipenv install lxml` tiobeindexpy worked fine.

**Comment by amrrs** [comment]
I faced this when I used it in https://repl.it/ . I'll probably try to add this as another dependency in the next version. Thanks for reporting!

**Comment by matteoredaelli** [comment]
Yes, I got the same dependency issue
